### ISSUE TITLE
언팩할때 오류뜹니다

### ISSUE THREAD

**Issue by sukkun1101** [DuelitDev/ModsPlease#1]
C:\Users\richa\ModsPlease-1.0.0>python packer.py -d "C:\Users\richa\new2\Art.dat" "C:users\richa"
Traceback (most recent call last):
  File "C:\Users\richa\ModsPlease-1.0.0\packer.py", line 193, in <module>
    unpack(*sys.argv[2:4])
  File "C:\Users\richa\ModsPlease-1.0.0\packer.py", line 143, in unpack
    operator = file.read(1).decode("utf-8")
ValueError: read of closed file

패킹은 잘 되는데 언패킹 할때는 오류뜨면서 안됩니다. 확인해주시길 바랍니다

**Comment by devrelu** [comment]
오류 수정했습니다. 감사합니다.
